# Generated by Django 4.0 on 2023-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('rpassword', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='work',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(max_length=100),
        ),
    ]
