# Generated by Django 4.0 on 2023-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_register_work_name_alter_artist_work_alter_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
